# Copyright 2025 ACCESS-NRI and contributors. See the top-level COPYRIGHT file for details.
# SPDX-License-Identifier: Apache-2.0

# =========================================================================================
# Generate remapping weights from an ESMF mesh file for remapping a runoff field
# from an unmasked mesh to a masked mesh without losing any water volume. Each field on the
# unmasked mesh is mapped to the nearest ocean cell in the resulting weights.
#
# To run:
#   python generate_rof_weights.py --mesh_filename=<input_file> --weights_filename=<output_file>
#
# This script currently supports mesh files in the ESMF unstructed mesh format.
#
# There is not enough memory on the gadi login node to run this, its simplest to run in
# a terminal through are.nci.org.au
#
# The run command and full github url of the current version of this script is added to the
# metadata of the generated weights file. This is to uniquely identify the script and inputs used
# to generate the mesh file. To produce weights files for sharing, ensure you are using a version
# of this script which is committed and pushed to github. For mesh files intended for released
# configurations, use the latest version checked in to the main branch of the github repository.
#
# Contact:
#   Anton Steketee <anton.steketee@anu.edu.au>
#
# Dependencies:
#   esmpy, xarray and scipy
# =========================================================================================


import xarray as xr
import esmpy
from sklearn.neighbors import BallTree
from scipy.ndimage import binary_dilation
import numpy as np
from copy import copy

from pathlib import Path
import sys

path_root = Path(__file__).parents[1]
sys.path.append(str(path_root))
from scripts_common import get_provenance_metadata

# these are lat, lon pairs to represent where high volumes on runoff enter the ocean
SPREAD_POINTS = [
    (-0.125, 310.625),
    (8.625, 299.375),
    (66.125, 196.375),
    (71.875, 82.875),
    (72.125, 128.875),
    (73.375, 106.625),
]

# Buffer (degrees) around spread_points to spread from
SRC_DIST = 1

# Number of cells to spread to
SPREAD_N = 75

# Decay distance when calculating spreading weights
FOLD = 15

COMP_ENCODING = {"complevel": 1, "compression": "zlib"}  # compression settings to use


def mesh_area(mesh_filename):
    """
    Calculate area for each cell in a mesh. per CMEPS we are using the internally calculated areas, not the user provided ones.
    """

    model_mesh = esmpy.Mesh(
        filename=mesh_filename,
        filetype=esmpy.FileFormat.ESMFMESH,
    )

    fld = esmpy.Field(model_mesh, meshloc=esmpy.MeshLoc.ELEMENT)

    fld.get_area()

    return copy(fld.data)


class Rof_Remapping_Weights:

    def __init__(self, mesh_filename, weights_filename, nx, ny, spread):
        # We need to generate remapping weights for use in the mediator, such that the overall volume of runoff is conserved
        # and no runoff is mapped onto land cells. Inside the mediator, the grid doesn't change as we run the mediator with
        # the ocean grid (the DROF component does the remapping from JRA grid to mediator grid). Therefore we use the
        # same _mesh_file for the input and output mesh, however this same function would work for differing input and
        # output meshes

        # From https://earthsystemmodeling.org/docs/release/ESMF_5_2_0rp3/ESMF_refdoc/node3.html :
        # " The indices and weights generated by ESMF_FieldRegridStore() are stored in the output file as variables col, row
        # and S. Where col and row are the indices to the source and the destination grid cells. These are a one-dimension
        # array with length defined by dimension n_s. S is the weight which is multiplied by the source value indicated by
        # col and then summed with the destination value indicated by row to build the final interpolated value of the destination.

        self.mesh_filename = mesh_filename
        self.mesh_ds = xr.open_dataset(mesh_filename)

        if len(self.mesh_ds.elementMask) != ny * nx:
            raise RuntimeError("ny * nx does not equal number of elements in mesh file")

        self.ny = ny
        self.nx = nx
        self.weights_f = weights_filename
        self.spread = spread

    def target_masks(self):
        """
        create masks for for runoff can be placed when being placed at coast (nospread)
        or being spread
        """
        # make new mask of land plus one adjacent cell of ocean
        ocn_mask = self.mesh_ds.elementMask.values == 1
        land_neighbours = binary_dilation(np.reshape(ocn_mask, (self.ny, self.nx)) == 0)
        land_neighbours = land_neighbours.flatten()

        # target for no spread runoff is ocean cells which are adjacent land
        self.target_mask_nospread = xr.DataArray(
            (land_neighbours & ocn_mask) == 1, dims="elementCount"
        )

        # target for spread runoff is whole ocean
        self.target_mask_spread = self.mesh_ds.elementMask == 1

    def source_mask(self):
        """
        For a the mesh dataset, extract the landmask, and
        then for the list of spread_points provided, spread them dist degrees
        """
        spread_mask = np.zeros_like(self.mesh_ds.elementMask.values)

        if self.spread:

            lon = self.mesh_ds.centerCoords[:, 0].values
            lat = self.mesh_ds.centerCoords[:, 1].values

            for plat, plon in SPREAD_POINTS:

                # Handle longitude wraparound correctly
                dlon = ((lon - plon + 180) % 360) - 180
                dlat = lat - plat

                point_mask = (abs(lat - plat) <= SRC_DIST) & (abs(dlon) <= SRC_DIST)

                spread_mask |= point_mask

        self.spread_source_mask = xr.DataArray(spread_mask == 1, dims="elementCount")

    def spread_weights(self):
        """
        For each of the spread and nospread target masks, use a ball tree to find nearest ocean cells.
        For cells in the spread source mask, spread with exponential decay away from the cell
        For cells ourside this mask, may to the closes ocean cell only.
        """

        # Haversine distances expect lat first, lon second, so index coordDim backwards
        center_coords_rad = np.deg2rad(self.mesh_ds.centerCoords.isel(coordDim=[1, 0]))

        # Make BallTrees from the target cells
        if self.spread:

            mask_tree_spread = BallTree(
                center_coords_rad.where(self.target_mask_spread, drop=True),
                metric="haversine",
            )
            target_mask_spread_i = self.mesh_ds.elementCount.where(
                self.target_mask_spread, other=0, drop=True
            )  # Index for the target_mask (other=0 preserves integer dtype)

        mask_tree_nospread = BallTree(
            center_coords_rad.where(self.target_mask_nospread, drop=True),
            metric="haversine",
        )
        target_mask_nospread_i = self.mesh_ds.elementCount.where(
            self.target_mask_nospread, other=0, drop=True
        )

        # Using the Trees, look up the nearest ocean cell to every destination grid cell in our weights file. Note our
        # weights are indexed from 1 (i.e. Fortran style) but xarray starts from 0 (i.e. python style), so subract one from
        # our destination grid cell indices.

        # input is all cells
        in_coords_rad = np.deg2rad(self.mesh_ds.centerCoords.isel(coordDim=[1, 0]))

        # nearest 1 - no spread
        i_1 = mask_tree_nospread.query(
            in_coords_rad,
            k=1,
            return_distance=False,
        )
        if self.spread:

            # nearest N - spread
            dist_N, i_N = mask_tree_spread.query(
                in_coords_rad,
                k=SPREAD_N,
                return_distance=True,
            )

        # make 2d array of indices and weights, then fill with spread/no_spread depending on the row
        n = len(center_coords_rad)
        indices = np.full((n, SPREAD_N), -1, dtype=int)
        weights = np.zeros((n, SPREAD_N), dtype=float)

        # we made i_1 and i_N for all source cells
        # select spread_i for spreading and no_spread_i for no spreading

        # Nospread points
        nospread_i = self.mesh_ds.elementCount.where(
            self.spread_source_mask == False, other=0, drop=True
        ).astype(int)
        row = target_mask_nospread_i[i_1[nospread_i, 0]]

        # Get the mesh element areas and adjust for area change between the
        # source cell (i) and destination (row)
        area = mesh_area(self.mesh_filename)

        indices[nospread_i, 0] = row
        weights[nospread_i, 0] = area[nospread_i] / area[row]

        # Spread points
        if self.spread:

            spread_i = self.mesh_ds.elementCount.where(
                self.spread_source_mask, other=0, drop=True
            ).astype(int)
            row = np.zeros((len(spread_i), SPREAD_N), dtype=int)

            for i in range(0, SPREAD_N):
                row[:, i] = target_mask_spread_i[i_N[spread_i, i]]

            new_area = area[row]

            # Exponential weights
            w = np.exp(-dist_N[spread_i] / FOLD)

            area_frac = [area / new_area[i] for i, area in enumerate(area[spread_i])]

            for i in range(0, len(w)):
                w[i] /= np.sum(w[i] / area_frac[i])

            indices[spread_i] = row
            weights[spread_i] = w

        # Flatten sparse structure
        col = np.repeat(self.mesh_ds.elementCount, SPREAD_N)
        row = indices.ravel()
        S = weights.ravel()

        self.create_weights_file(row, col, S)

    def create_weights_file(self, row, col, S):
        """ "
        For provided data (row, col, S) save it to a newtcdf weights file
        """

        # Convert to ESMF 1-based indexing
        row += 1
        col += 1

        weights_ds = xr.Dataset()
        weights_ds["col"] = xr.DataArray(data=col, dims="n_s")
        weights_ds["row"] = xr.DataArray(data=row, dims="n_s")
        weights_ds["S"] = xr.DataArray(data=S, dims="n_s")

        # Remove zero weights
        weights_ds = weights_ds.where(weights_ds["S"] != 0, drop=True)

        # add global attributes
        weights_ds.attrs = {
            "gridType": "unstructured mesh",
        }

        # add git info to history
        weights_ds.attrs |= get_provenance_metadata([self.mesh_filename])

        # save (compressed)
        encoding = {}
        for iVar in weights_ds.data_vars:
            encoding[iVar] = COMP_ENCODING
        weights_ds.to_netcdf(self.weights_f, encoding=encoding)


def gen_rof_weights(mesh_filename, weights_filename, nx, ny, spread=True):
    """
    Conveniance function for doing the whole weights generation
    """
    rof_weights = Rof_Remapping_Weights(mesh_filename, weights_filename, nx, ny, spread)
    rof_weights.target_masks()
    rof_weights.source_mask()
    rof_weights.spread_weights()


def main():
    parser = argparse.ArgumentParser(
        description="Create an remapping weights to transfer runoff from unmasked mesh to masked mesh using ESMF mesh file."
    )

    parser.add_argument(
        "--mesh_filename",
        type=str,
        required=True,
        help="The path to the mesh file specifying the model grid and land mask.",
    )
    parser.add_argument(
        "--nx",
        type=int,
        required=True,
        help="Number of global cells in x directon",
    )
    parser.add_argument(
        "--ny",
        type=int,
        required=True,
        help="Number of global cells in y directon",
    )
    parser.add_argument(
        "--weights_filename",
        type=str,
        required=True,
        help="The path to the weights file to output (netcdf).",
    )
    parser.add_argument(
        "--spread",
        action=argparse.BooleanOptionalAction,
        required=False,
        default=True,
        help="Spread large rivers",
    )

    args = parser.parse_args()

    return gen_rof_weights(
        args.mesh_filename, args.weights_filename, args.nx, args.ny, args.spread
    )


if __name__ == "__main__":
    import argparse

    main()
