#!/usr/bin/bash
#PBS -l ncpus=208
#PBS -l mem=1000GB 
#PBS -q expresssr
#PBS -l walltime=01:00:00
#PBS -l wd
#PBS -l storage=gdata/tm70+gdata/xp65
#PBS -l jobfs=100GB
#PBS -v PYTHONNOUSERSITE=True
#PBS -P tm70

module use /g/data/xp65/public/modules ; module load conda/analysis3-25.06

python3 /g/data/tm70/as2285/om3-scripts/payu_config/archive_scripts/concat_ice_daily.py