# This workflow will install dependencies, run tests and the black-formatter

name: om3_scripts

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Code formatting
      uses: psf/black@stable
      with:
        options: "--check --verbose --diff"

  test:
    needs: formatting
    runs-on: ubuntu-latest
    container:
      image: rockylinux/rockylinux:8
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install nco
      run: |
        dnf install https://dl.fedoraproject.org/pub/epel/8/Everything/x86_64/Packages/n/nco-4.8.1-1.el8.x86_64.rpm
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r test/test_requirements.txt
    - name: Test with pytest
      run: |
        python -m pytest -m "not broken" -vvv
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v3
      env:
        CODEOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
