# This workflow will install dependencies, run tests and the black-formatter

name: om3_scripts

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Code formatting
      uses: psf/black@stable
      with:
        options: "--check --verbose --diff"


  test:
    needs: formatting
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']

    steps:
    - uses: actions/checkout@v6
    - name: Setup conda environment
      uses: conda-incubator/setup-miniconda@v4
      with:
        python-version: ${{ matrix.python-version }}
        activate-environment: om3-scripts-test
        environment-file: test/test_env.yaml
    - name: List installed packages
      run: |
        conda env list
        conda list
    - name: Test with pytest
      run: |
        python -m pytest -m "not broken" -v -s
